name: "applying-behavior"
version: "1.0.0"
model: "sonnet"
color: "orange"

description: |
  Apply behavioral physics only (sync strategy, timing, confirmation).
  Use when timing/sync is wrong but looks and animation are fine.
  For full physics (behavioral + animation + material), use /craft.

triggers:
  - "/behavior"
  - "fix the timing"
  - "sync is wrong"
  - "feels too slow"
  - "needs confirmation"
  - "make it optimistic"

examples:
  - input: "/behavior \"claim button — feels too slow\""
    description: "Reduce timing while respecting effect"
  - input: "/behavior \"delete — needs confirmation\""
    description: "Add confirmation step"
  - input: "/behavior \"like button — should be snappier\""
    description: "Switch to optimistic sync"

inputs:
  - name: description
    type: string
    required: true
    description: "Component and behavioral adjustment"

outputs:
  - path: "src/components/*.tsx"
    description: "Component with adjusted behavioral physics"
  - path: "grimoires/sigil/taste.md"
    description: "Updated taste signals"

context_files:
  - path: ".claude/rules/01-sigil-physics.md"
    required: true
  - path: ".claude/rules/02-sigil-detection.md"
    required: true
  - path: ".claude/rules/04-sigil-protected.md"
    required: true
  - path: ".claude/rules/06-sigil-taste.md"
    required: true
  - path: "grimoires/sigil/taste.md"
    required: false

zones:
  state:
    paths:
      - grimoires/sigil/
    permission: read-write
  app:
    paths:
      - src/
      - app/
      - components/
    permission: read-write
