name: "distilling-components"
version: "1.0.0"
model: "sonnet"
color: "cyan"

description: |
  Distill a task into craft-able components.
  Bridge between architecture (Loa) and physics (Sigil).
  Extracts component essences with physics hints ready for /craft.

triggers:
  - "/distill"
  - "break this down into components"
  - "what components do I need"
  - "extract components from"

examples:
  - input: "/distill \"implement mobile view\""
    description: "Extract mobile components with physics hints"
  - input: "/distill \"add checkout flow\""
    description: "Identify checkout components and effects"
  - input: "/distill \"redesign settings page\""
    description: "Break down settings into craft-able pieces"

inputs:
  - name: task
    type: string
    required: true
    description: "Task, feature, or requirement to distill"

outputs:
  - path: "stdout"
    description: "Component list with physics hints ready for /craft"

context_files:
  - path: ".claude/rules/02-sigil-detection.md"
    required: true
  - path: ".claude/rules/08-sigil-lexicon.md"
    required: true
  - path: "grimoires/loa/prd.md"
    required: false
  - path: "grimoires/loa/sdd.md"
    required: false
  - path: "grimoires/loa/sprint.md"
    required: false

zones:
  app:
    paths:
      - src/
      - app/
      - components/
    permission: read
