name: initializing-sigil
description: Initialize Sigil v4 Design Physics Engine on a repository
version: "0.5.0"

triggers:
  - "/sigil-setup"

examples:
  - input: "/sigil-setup"
    description: "Initialize Sigil v4 on current repo"

inputs: []

outputs:
  # Constitution layer
  - path: grimoires/sigil/constitution/physics.yaml
    description: Motion timing and sync strategies
  - path: grimoires/sigil/constitution/fidelity.yaml
    description: Fidelity Ceiling (Mod Ghost Rule)
  - path: grimoires/sigil/constitution/vocabulary.yaml
    description: Term → zone/physics mapping
  - path: grimoires/sigil/constitution/workflow.yaml
    description: Team methodology rules

  # Moodboard layer
  - path: grimoires/sigil/moodboard/evidence/
    description: Evidence screenshots and artifacts
  - path: grimoires/sigil/moodboard/essence.yaml
    description: Product soul (populated by /envision)

  # State layer
  - path: grimoires/sigil/state/decisions/
    description: Decision records
  - path: grimoires/sigil/state/eras/era-1.yaml
    description: Era versioning template

  # Taste Key
  - path: .sigil/taste-key.yaml
    description: Taste Key authority definition

  # Configuration
  - path: .sigilrc.yaml
    description: Framework configuration
  - path: .sigil-setup-complete
    description: Setup completion marker
  - path: .sigil-version.json
    description: Version tracking
