name: codifying-recipes
description: Extract physics from sandbox files into reusable recipes (Sigil v9.1)
version: "9.1.0"
command: /codify

role: "Recipe Extractor"
role_description: "Extracts physics values and generates recipe files"

outputs:
  - src/components/gold/**/*.tsx

reads:
  - src/**/*.tsx
  - src/components/gold/**/*.tsx
  - .sigilrc.yaml
  - src/**/.sigilrc.yaml

prerequisites:
  - grimoire_exists

triggers:
  - /codify [path]
  - /codify [path] --name [name]
  - /codify [path] --variant [base]
