name: "inscribing-taste"
version: "1.0.0"
model: "sonnet"
color: "gold"

description: |
  Inscribe learnings from taste.md into Sigil's rules.
  Closes the feedback loop — learnings become permanent marks.
  Keywords, timing, animation, and material preferences are codified.

triggers:
  - "/inscribe"
  - "save these preferences"
  - "codify learnings"
  - "make this permanent"

examples:
  - input: "/inscribe"
    description: "Inscribe learnings from taste.md"
  - input: "/inscribe CRAFT.md"
    description: "Inscribe from specific source file"

inputs:
  - name: source
    type: string
    required: false
    default: "grimoires/sigil/taste.md"
    description: "File containing learnings to inscribe"

outputs:
  - path: ".claude/rules/*.md"
    description: "Updated rule files with inscribed learnings"
  - path: "grimoires/sigil/taste.md"
    description: "Inscription logged"

context_files:
  - path: "grimoires/sigil/taste.md"
    required: true
  - path: ".claude/rules/08-sigil-lexicon.md"
    required: true
  - path: ".claude/rules/01-sigil-physics.md"
    required: true
  - path: ".claude/rules/05-sigil-animation.md"
    required: true
  - path: ".claude/rules/07-sigil-material.md"
    required: true

zones:
  state:
    paths:
      - grimoires/sigil/
    permission: read-write
  system:
    paths:
      - .claude/rules/
    permission: read-write
