name: crafting-guidance
description: Provide design guidance with value/flaw/lens awareness during implementation
version: "9.1.0"

triggers:
  - "/craft"

examples:
  - input: "/craft"
    description: "Get general design guidance"
  - input: "/craft src/components/Button.tsx"
    description: "Get zone-specific guidance for a file"
  - input: "/craft \"How should modals animate?\""
    description: "Ask a design question"
  - input: "/craft \"Does this work for all lenses?\""
    description: "Validate component against all defined lenses"

inputs:
  - name: context
    type: string
    required: false
    description: File path or design question

outputs: []

# v9.1: Removed phantom file references (soul-binder, lens-array don't exist)
# Context now loaded from grimoires/sigil/constitution/ via process layer
checks:
  - path: grimoires/sigil/constitution/protected-capabilities.yaml
    description: Check for protected capability violations
  - path: grimoires/sigil/constitution/vocabulary.yaml
    description: Check vocabulary term consistency
  - path: grimoires/sigil/constitution/physics.yaml
    description: Check physics timing constraints
