name: blockchain-inspector
version: "1.0"
description: Read-only on-chain state inspection for web3 debugging

triggers:
  - "/observe diagnose"
  - "compare on-chain"
  - "verify contract state"
  - "check blockchain state"
  - "read contract"

context_files:
  - path: "envio.config.ts"
    required: false
    purpose: "Get RPC URLs and contract addresses"
  - path: ".env"
    required: false
    purpose: "Environment variables including RPC_URL"
  - path: "src/abi/"
    required: false
    purpose: "Contract ABIs for decoding"
  - path: "artifacts/"
    required: false
    purpose: "Compiled contract artifacts"

capabilities:
  - id: read_contract
    description: "Read public state from smart contracts"
    methods:
      - viem.readContract
      - cast call
      - eth_call JSON-RPC

  - id: batch_read
    description: "Read multiple contract values in one call"
    methods:
      - viem.multicall
      - sequential cast calls

  - id: get_block
    description: "Get current block number"
    methods:
      - eth_blockNumber
      - cast block-number

  - id: compare_sources
    description: "Compare on-chain state with indexed data"
    methods:
      - on-chain read + envio query comparison

output_formats:
  - yaml  # For craft-state.md integration
  - display  # For terminal output

limitations:
  - "Read-only - cannot modify state"
  - "Requires ABI for complex decoding"
  - "Rate limited on public RPCs"
  - "Cannot read private variables"

integration:
  observe_diagnose: true
  craft_state: true
