name: "animating-motion"
version: "1.0.0"
model: "sonnet"
color: "green"

description: |
  Apply animation physics only (timing, easing, springs).
  Use when movement feels off but behavior and looks are fine.
  For full physics (behavioral + animation + material), use /craft.

triggers:
  - "/animate"
  - "fix the animation"
  - "movement feels off"
  - "make it snappier"
  - "more organic"
  - "less bouncy"

examples:
  - input: "/animate \"button — snappier\""
    description: "Increase animation speed"
  - input: "/animate \"modal — more organic feel\""
    description: "Soften spring values"
  - input: "/animate \"dropdown — less bouncy\""
    description: "Increase damping"

inputs:
  - name: description
    type: string
    required: true
    description: "Component and animation adjustment"

outputs:
  - path: "src/components/*.tsx"
    description: "Component with adjusted animation"
  - path: "grimoires/sigil/taste.md"
    description: "Updated taste signals"

context_files:
  - path: ".claude/rules/05-sigil-animation.md"
    required: true
  - path: ".claude/rules/06-sigil-taste.md"
    required: true
  - path: "grimoires/sigil/taste.md"
    required: false

zones:
  state:
    paths:
      - grimoires/sigil/
    permission: read-write
  app:
    paths:
      - src/
      - app/
      - components/
    permission: read-write
