name: crafting-components
description: Generate UI components using zone-appropriate physics (Sigil v9.1)
version: "9.1.0"
command: /craft

role: "Apprentice Smith"
role_description: "Generates components using physics. No raw physics outside sandbox."

outputs: []  # Generates code, not state files

reads:
  # Zone config
  - .sigilrc.yaml
  - src/**/.sigilrc.yaml
  # Gold components
  - src/components/gold/**/*.tsx
  # Physics
  - src/components/gold/hooks/useMotion.ts
  - grimoires/sigil/constitution/physics.yaml

prerequisites:
  - grimoire_exists

context_injection: true

triggers:
  - /craft [description]
  - /craft [description] --file [path]
  - /craft [description] --zone [zone]
