name: "surveying-patterns"
version: "1.0.0"
model: "sonnet"
color: "teal"

description: |
  Health report on pattern authority and component usage.
  Shows which components are canonical (Gold), established (Silver),
  or experimental (Draft). Authority is computed, not configured.

triggers:
  - "/garden"
  - "show pattern authority"
  - "component health"
  - "authority report"
  - "what components are canonical"

examples:
  - input: "/garden"
    description: "Generate full authority report"

inputs: []

outputs:
  - path: "stdout"
    description: "Authority distribution and recommendations"

context_files:
  - path: "src/components/"
    required: false
  - path: ".claude/rules/01-sigil-physics.md"
    required: true

integrations:
  - ck

no_questions:
  - "Should I promote this component?"
  - "Do you want to change the tier?"

zones:
  app:
    paths:
      - src/
      - app/
      - components/
    permission: read
