name: "crafting-physics"
version: "1.0.0"
model: "sonnet"
color: "purple"

description: |
  Apply design physics to any UX-affecting change. Three layers:
  Behavioral + Animation + Material = Feel. Use for new components,
  refinements, configurations, data patterns, and polish passes.

triggers:
  - "/craft"
  - "create component"
  - "build a button"
  - "generate UI"
  - "craft a"

examples:
  - input: "/craft \"claim button\""
    description: "Generate financial component with full physics"
  - input: "/craft \"glassmorphism card with spring animation\""
    description: "Material + animation specified"
  - input: "/craft \"improve light mode readability\""
    description: "Refine existing configuration"

inputs:
  - name: description
    type: string
    required: true
    description: "What to craft — new, refine, or polish"
  - name: url
    type: string
    required: false
    description: "URL for visual verification after generation"

outputs:
  - path: "src/components/*.tsx"
    description: "Generated component"
  - path: "grimoires/sigil/taste.md"
    description: "Updated taste signals"

context_files:
  - path: ".claude/rules/00-sigil-core.md"
    required: true
  - path: ".claude/rules/01-sigil-physics.md"
    required: true
  - path: ".claude/rules/02-sigil-detection.md"
    required: true
  - path: ".claude/rules/03-sigil-patterns.md"
    required: true
  - path: ".claude/rules/04-sigil-protected.md"
    required: true
  - path: ".claude/rules/05-sigil-animation.md"
    required: true
  - path: ".claude/rules/06-sigil-taste.md"
    required: true
  - path: ".claude/rules/07-sigil-material.md"
    required: true
  - path: ".claude/rules/08-sigil-lexicon.md"
    required: true
  - path: "grimoires/sigil/taste.md"
    required: false
  - path: "grimoires/sigil/context/"
    required: false

zones:
  state:
    paths:
      - grimoires/sigil/
    permission: read-write
  app:
    paths:
      - src/
      - app/
      - components/
    permission: read-write
