name: "styling-material"
version: "1.0.0"
model: "sonnet"
color: "blue"

description: |
  Apply material physics only (surface, shadow, typography).
  Use when looks are wrong but behavior and animation are fine.
  For full physics (behavioral + animation + material), use /craft.

triggers:
  - "/style"
  - "fix the styling"
  - "change the look"
  - "make it look"
  - "glassmorphism"
  - "material treatment"

examples:
  - input: "/style \"glassmorphism card\""
    description: "Apply glass surface treatment"
  - input: "/style \"minimal outline button\""
    description: "Reduce visual weight"
  - input: "/style \"elevated card with soft shadow\""
    description: "Add depth with shadows"

inputs:
  - name: description
    type: string
    required: true
    description: "What surface treatment to apply"

outputs:
  - path: "src/components/*.tsx"
    description: "Component with correct material treatment"
  - path: "grimoires/sigil/taste.md"
    description: "Updated taste signals"

context_files:
  - path: ".claude/rules/07-sigil-material.md"
    required: true
  - path: ".claude/rules/08-sigil-lexicon.md"
    required: true
  - path: ".claude/rules/06-sigil-taste.md"
    required: true
  - path: "grimoires/sigil/taste.md"
    required: false

zones:
  state:
    paths:
      - grimoires/sigil/
    permission: read-write
  app:
    paths:
      - src/
      - app/
      - components/
    permission: read-write
