name: "mounting-sigil"
version: "1.0.0"
model: "sonnet"
color: "purple"

description: |
  Install Sigil design physics framework onto a repository.
  Sets up grimoires/sigil/ structure, initializes taste.md,
  and prepares the project for physics-driven component generation.
  "The Sigil mounts the repository, preparing to craft."

triggers:
  - "/mount"
  - "mount sigil"
  - "install sigil"
  - "setup sigil framework"
  - "add sigil to project"

examples:
  - context: "User wants to add Sigil to their existing project"
    user_says: "I want to use Sigil on this project"
    agent_action: "Launch mounting-sigil to install physics rules and initialize taste log"
  - context: "New repository needs Sigil setup"
    user_says: "Mount Sigil on this repo"
    agent_action: "Launch mounting-sigil to prepare the repository for design physics"
  - context: "User is setting up a fork or clone"
    user_says: "Install the Sigil framework here"
    agent_action: "Launch mounting-sigil to set up physics rules and state directories"

zones:
  system:
    path: ".claude"
    permission: "write"
  state:
    paths: ["grimoires/sigil"]
    permission: "read-write"
  app:
    paths: ["src", "lib", "app"]
    permission: "none"

dependencies: []

inputs:
  - name: "stealth"
    type: "flag"
    required: false
    description: "Add State Zone to .gitignore"
  - name: "branch"
    type: "string"
    required: false
    default: "main"
    description: "Sigil branch to use"

outputs:
  - path: ".sigil-version.json"
    description: "Version manifest"
  - path: "grimoires/sigil/"
    description: "State Zone for taste accumulation"
  - path: "grimoires/sigil/taste.md"
    description: "Taste signal log"
